---
deployment:
    tasks:
        - export DEPLOYPATH=/home3/ameridg3/public_html/
        - /bin/cp -R css $DEPLOYPATH
        - /bin/cp -R images $DEPLOYPATH
        - /bin/cp -R js $DEPLOYPATH
        - /bin/cp -R templates $DEPLOYPATH
        - /bin/cp about.php $DEPLOYPATH
        - /bin/cp contact.php $DEPLOYPATH
        - /bin/cp databaseconnect.php $DEPLOYPATH
        - /bin/cp index.php $DEPLOYPATH
        - /bin/cp products.php $DEPLOYPATH
        - /bin/cp rails.php $DEPLOYPATH
        - /bin/cp stairs.php $DEPLOYPATH
# this needs to be updated for every new file that gets added
# the -R is for folders. Deploypath tells it where to send the files on the server
